Agregada funcionalidad de eliminar un sandwich
ezez8/PythonMiniProyecto1 pull request #11
Opened 2020-11-21 17:47 UTC by ezez8

## Propósito

Funcionalidad de eliminar un sandwich

### Tareas elaboradas

Agregada e implementada clase DeleteSandwichView, Implementado método delete_sandwich en clase Controller

## Características

DeleteSandwich imprime por consola la lista de sandwichs de la orden
delete_sandwich contiene la lógica necesaria para eliminar un sandwich

2020-11-21 17:51 UTC, Robertocd98 approved these changes
compilado y todo funciona de manera correcta

2020-11-21 18:53 UTC, yeisson-venencia requested changes
Buen trabajo Ezequiel, funcionalmente está correcto. Te dejo acá unas observaciones:
- Debes actualizar la rama  con develop para eliminar los conflictos de merge
- Creo que se deberia limpiar la pantalla luego de eliminar.Al menos preguntar si se desea continuar para llevarlo de nuevo a la vista de eleminar o al menu principal de la orden
- Intenta que la vista no se realicen calculos. En la clase sandwich ya hay una función que te devuelve la descripción del sandwich

2020-11-21 23:35 UTC, yeisson-venencia requested changes
Revisado todos los cambios Ezequiel. A contnuación las observaciones:
- Cambir todo lo que diga 'Pago' por 'Payment' (la función del controlador y la view)
-En la ventana de Delete. En el display order, utiliza tambien la funcion de los sandwich get_full_description para no repetir código
- Al pagar, pregunta si de sea efectuar el pago. Si te dice que SI le muestras "Gracias por su compra. Vuelva pronto" luego lo de "presione ENTER para continuar" y borras la orden (con self.model.reset_order() ) y lo mandas al primer menu (Welcome). Si te dice que no o cualquier otra cosa lo mandas al menu anterio (self.order_menu())

2020-11-23 00:03 UTC, yeisson-venencia approved these changes
Perfecto. Muy buen trabajo Ezequiel!!

2020-11-23 01:20 UTC, merged